H1 = struct(...
    'FontSize', 15, ...
    'HorizontalAlignment', 'left', ...
    'VerticalAlignment', 'middle', ...
    'LineStyle', 'none', ...
    'Units', 'normalized'); 
H2 = struct(...
    'FontSize', 12, ...
    'HorizontalAlignment', 'left', ...
    'VerticalAlignment', 'middle', ...
    'LineStyle', 'none', ...
    'Units', 'normalized'); 
H3 = struct(...
    'FontSize', 10, ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'middle', ...
    'LineStyle', 'none', ...
    'Units', 'normalized'); 

S1 = struct(...
    'FontSize', 10, ...
    'BackgroundColor', [0.96,0.96,0.96]);
S2 = struct(...
    'FontSize', 12, ...
    'BackgroundColor', [0.96,0.96,0.96]);
S3 = struct(...
    'FontSize', 18, ...
    'FontWeight', 'bold', ...
    'ForegroundColor', [0.8,0.1,0.1], ...
    'BackgroundColor', [0.96,0.96,0.96]);
S4 = struct(...
    'FontSize', 8, ...
    'BackgroundColor', [0.96,0.96,0.96]);

app_styles = struct(...
    'H1', H1, ...
    'H2', H2, ...
    'H3', H3, ...
    'AppFontSize', 10, ...    
    'TraceAxes_LineWidth', 1.5, ...
    'TraceAxes_FontSize', 12, ...
    'TraceAxes_TitleFontSizeMultiplier', 1.2, ...
    'TraceAxes_LabelFontSizeMultiplier', 1.1, ...
    'TraceAxes_TitleFontWeight', 'normal', ...
    'TraceAxes_TickDir', 'out', ...
    'TraceAxes_BorderWidth', 1, ...
    'TraceAxes_BoxOption', 'off', ... % 'on' or 'off'
    'TraceAxes_ToolbarOption', 'off', ... % 'on' or 'off' 
    'S1', S1, ...
    'S2', S2, ...
    'S3', S3, ...
    'S4', S4 ...
    );

save('app_styles.mat', 'app_styles');
    
    